### ISSUE TITLE
Should dashboard buttons allow html rather than just text?

### ISSUE THREAD

**Issue by pjvandehaar** [statgen/locuszoom#104]
Right now,

- `component.text` is plain text.  I'd like to use HTML for glyphicons but don't need it.
- `component.title` is plain text
- `title_component.title` is html
- `menu_component.button_html` is plain text
- `menu_component.menu_html` is html
- `covariates_component.button_html` is plain text

Should all of these allow arbitrary HTML?

**Comment by Frencil** [comment]
All of the above should be safe to be interpreted as HTML. In general, any element being defined by the layout that's outside of the SVG context (so dashboard elements, tooltips, etc.) should accept arbitrary HTML where they accept arbitrary stings.

The *only* exception would be places where strings are being used for title attributes (e.g. `LocusZoom.Dashboard.Component.Button.title`) as HTML doesn't make sense in that context.

XSS is not a concern here... any `<script>` tags pumped through LZ's HTML generation methods would not be executed as browsers don't automatically execute dynamic script tags. And since everything's client-side anyway if somebody really wanted to execute arbitrary JS they certainly could without needing to use LZ's HTML passthroughs.

**Comment by pjvandehaar** [comment]
Thanks for explaining about the XSS.  I always assumed the browser evaluated scripts on `node.innerHTML = string`, but apparently that's jquery [here](https://github.com/jquery/jquery/blob/master/src/manipulation.js#L192), not [documented](https://api.jquery.com/html/#html2).

**Comment by Frencil** [comment]
Fixed in [a39f647](https://github.com/statgen/locuszoom/commit/a39f647391d3d97cb23c93b241953c865f7debc7), will be included in v0.5.7.
