### ISSUE TITLE
local data, refVar

### ISSUE THREAD

**Issue by anujgoel1** [statgen/locuszoom#180]
Hi,
Sorry to bother with this request. 
I have my own summary statistics that I am using as JSON file for a region and am using your server API LDLZ2 for LD information.
What I really would like to do is have my own custom refVar rather than the "best". I am not able to achieve this. Not sure if I have not understood it clearly enough to implement this or this feature is not available in this scenario?
Many thanks for help/suggestion.
BW,
Anuj

**Comment by abought** [comment]
Anuj, 

We're always happy to help a new LocusZoom user.

The good news is that LZ absolutely supports this feature. There are two ways to set the "best" variant:

1. If you are using the "default" association plot layout, there is a tooltip option that you can click any point to "make (it the) LD reference".

![Screen Shot 2020-03-23 at 12 01 42 PM](https://user-images.githubusercontent.com/2957073/77336613-28c95e80-6cfe-11ea-880e-5379ca9d3507.png)

2. Even if you don't use the default layout, you can still set LD ref var via code before or after plot creation, by setting a variable in `plot.state`: eg to change it after the plot is drawn, and rerender: 
`plot.applyState( { ldrefvar: "16:53845487_C/A" });`

Since you are already using `LDLZ2` as your data source, note that this will even work in combination with the "LD population" dropdown menu, for any of several 1000G reference populations.

Here is a sample page showing both "custom ref var" and "LD population" UI in action:
https://my.locuszoom.org/gwas/236887/region/?chrom=16&start=53609247&end=54009247


If your goals are simple enough, you may not even need to use your own JSON file; our new tools allow association plots directly from an association file ([from tabixed data without uploading](https://statgen.github.io/localzoom/), or [upload to get additional features](my.locuszoom.org/))


Hope this helps- let us know if you have further questions!

**Comment by anujgoel1** [comment]
Great. Thanks Andy.
I had tried option 1 but wasnt what I had in mind. 
Option 2 did the trick for me. :)
Many thanks.
Best wishes,
Anuj.
