### ISSUE TITLE
Issue with geneLZ datasource URL

### ISSUE THREAD

**Issue by cgrace1978** [statgen/locuszoom#226]
I am using the geneLZ datasource within a "standard_association" plot with the API url: 
`https://portaldev.sph.umich.edu/api/v1/annotation/genes/
`
The gene panel is working in some  instances and not-working in other instances, I have included screen shots of two test pages I have generated.

HTML with gene panel working:
![image](https://user-images.githubusercontent.com/26602418/103892038-c998d700-50e2-11eb-8f03-35b1c0135af0.png)

![image](https://user-images.githubusercontent.com/26602418/103890158-7bce9f80-50df-11eb-860a-b543aee9f299.png)

HTML with gene panel not working:

![image](https://user-images.githubusercontent.com/26602418/103892059-d289a880-50e2-11eb-82a4-4ee530e60440.png)

![image](https://user-images.githubusercontent.com/26602418/103890188-88eb8e80-50df-11eb-8493-2dc8179026c2.png)

**Comment by abought** [comment]
Thanks for the report.

The error you are showing appears to be due to the external API (gnomAD) that we query for gene constraint information.

Two thoughts come to mind:

1. The version of LocusZoom you are using (0.10.1) is rather old. Newer versions (eg 0.12.2) have improved how we handle error messages from that API (we will still display gene information, just not overlay constraint info). 
2. We did introduce some minor breaking changes in 0.12.x, though I think the changes would be trivial for the example code you show. If using the older version is a firm requirement, we can assist you in disabling the gene constraint part of the request. (it involves understanding and modifying some aspects of LZ layout syntax though: upgrading versions is usually easier)

Does your error still occur with the newest LZ.js version? (newest stable version is 0.12.2)

**Comment by cgrace1978** [comment]
I've updated locuszoom.js to the latest version and now the genes are loaded correctly. Thanks for the help!
