### ISSUE TITLE
Manhattan plot and LocusZoom plot on the same page

### ISSUE THREAD

**Issue by jielab** [statgen/locuszoom#284]
Hi, guys:

Besides the classic **GWAS Catalog** and **LocusZoom**, recently there are **Gene Atlas**, **GWAS Atlas**, **IEU Open GWAS**, and **PheWeb** variants such as Pheweb.jp. All these are amazing and wonderful.

However, I am looking for something very simple: a webpage where I could upload GWAS or use existing GWAS to first display a Manhattan plot, and then click on anywhere on the plot (or a top loci table underneath it) to get a LocusZoom plot. **Just like Google Map, where we could ZOOM all out to see the whole earth, and we could also ZOOM all in to see a street block.**

Don't know if there is such a thing.

Thanks!

Jie

**Comment by abought** [comment]
Thanks for the interest! 

Our my.locuszoom.org service does provide such a feature, and might be worth a look (click any point to see a region plot, or see the table underneath for your own data). Example: https://my.locuszoom.org/gwas/236887/

Manhattan plots are a separate feature not built into the underlying LocusZoom.js library or the standalone [LocalZoom](https://statgen.github.io/localzoom/) tool. This is because GWAS files can be quite large, and it is useful to process the data once on a web server before rendering.

(Even google maps has to store many copies of imagery at different zoom levels! This is calculated ahead of time, rather than on every new request)

I hope this answers your question! If not, feel free to re-open this issue and we would be happy to follow up.
