### ISSUE TITLE
Missing SNP 

### ISSUE THREAD

**Issue by ariadnacilleros** [statgen/locuszoom#286]
Hello, 

I have uploaded the summary-statistics from a GWAS conditioned by primary signals, and I am not able to find my SNP. It happens the same with the summary-statistics from the original GWAS. All SNPs are detected correctly with the reference and alternative alleles, but this one (6:28782998 --> rs16897420) is not appearing although I have checked the alleles with the reference, is there any reason why is this happening? Is locusZoom performing any kind of filter such as MAF? 
Thank you so much!

Ariadna

**Comment by abought** [comment]
Thanks for the question. The word locuszoom can refer to several things, and each has slightly different rules for how it works. 

Can you clarify which version and tool you're having the problem with? Generally, the site my.locuszoom.org features our newest code and annotations. 

Other tools, like "old" locuszoom.org or the python command-line tool, may have very outdated annotations and are not officially supported.

**Comment by abought** [comment]
I haven't heard back in ~2 weeks, so I'm going to close this issue due to inactivity. But please feel free to follow up if the problem persists, esp in our most current tools like my.locuszoom.org.

Looking at the history in [dbSNP](https://www.ncbi.nlm.nih.gov/snp/rs16897420), it doesn't seem like this would be caused by a slightly older copy of dbSNP being used for the annotations (~2020, as that's when the my.locuszoom.org rsID matcher was released).
