### ISSUE TITLE
UMich SPH server is down?

### ISSUE THREAD

**Issue by vb-tony** [statgen/locuszoom#291]
Hello,

I am posting this here because I am not sure of the most appropriate contact for this. Please let me know if I should be directing this concern to another source.

I noticed that the University of Michigan School of Public Health servers seem to be having timeout issues (https://sph.umich.edu/). We are leveraging several of the UMich APIs for our LocusZoom plots including gene data, recombination data, and LD correlation data. Since these APIs are down, none of our LocusZoom plots are able to load. These APIs are the same ones that are used in the LocusZoom documentation.

Sample of APIs called:
- https://portaldev.sph.umich.edu/ld/
- https://portaldev.sph.umich.edu/api/v1/annotation/recomb/results/
- https://portaldev.sph.umich.edu/api/v1/annotation/genes/
- https://portaldev.sph.umich.edu/api/v1/statistic/single/

Is there a contact I can reach out to about this concern to see if it can be addressed? Or are there alternative resources we can tap into to pull this similar reference data for our plots?

Many thanks,
Tony

**Comment by welchr** [comment]
The university is currently under [a campus-wide outage due to a security incident](https://twitter.com/umichTECH). We've been down since Sunday afternoon with no ETA to restoration. We are told our servers are fine and that we need only wait for connectivity to be restored. But we unfortunately have no idea when that will be. 

All of the data behind the API is public and could be made available for download. However, the time it would take to setup both the API server and the separate LDServer, and ingest the data, is probably longer than it will take for service to be restored (though I am purely guessing at this point).

**Comment by vb-tony** [comment]
Thanks, Ryan! I really appreciate the prompt response.

Dang, sorry to hear about the outage. So it sounds like it would be easier to wait out the connectivity restoration rather than figure out a way to download the data. 

Do you happen to know if there is another resource we can go to download the public data at the moment? No worries if not. Hoping the connectivity gets restored soon.

**Comment by vb-tony** [comment]
Also, I'll go ahead and close this issue since the issue is known. Thanks again for sharing the context!

**Comment by welchr** [comment]
Our servers seem to have come back online and are responding to web traffic requests. Hopefully it will last. 

The LD panels used by the [ldserver](https://github.com/statgen/LDServer) are located here: https://portaldev.sph.umich.edu/ld_panels/

The API data needs some cleaning up to post. I suspect we may have a few conversations about transferring services to Google Cloud. During that process, I will try to get the data ready and uploaded somewhere.

**Comment by vb-tony** [comment]
Great news! Thanks so much for the update, Ryan!
