### ISSUE TITLE
Credible sets

### ISSUE THREAD

**Issue by MrFlick** [statgen/locuszoom#39]
We had a request from Andrew Morris to see if its feasible to display the credible set of variants for a particular association peak.

This feature request would involve two parts
- [x]  A data source (or transformation) to do the calculation based on the p-values (or test statistics) of all SNPs in a region. Each SNP would get a dichotomous label: in or out of the credible set.
- [x]  A way to visualize the SNPs in the credible set. This could either be some transformation on the p-value points or a separate annotation track.

**Comment by hyunminkang** [comment]
The calculation of credible set is relatively straightforward. There is a
NG paper where Andrew Morris is the first author, which would be one of the
easiest to implement.

Hyun.

**Comment by welchr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credible sets calculation](https://trello.com/c/UyKbQllE/2-credible-sets-calculation)

**Comment by welchr** [comment]
We had some back and forth via email and wanted to update current status here. 

Goncalo/Hyun suggested we start with the simple statistic: 

![image](https://user-images.githubusercontent.com/165778/31912974-c35efd94-b813-11e7-9366-a4990a9d31f2.png)

Where Zi is the z-statistic for each variant in the region. 

Since we only have log p-values, we need to convert them back into a z-statistic (or directly to Z_i^2). Typically you would do this with: 

![image](https://user-images.githubusercontent.com/165778/31913338-eb53acb8-b814-11e7-9214-c275c13f5897.png)

Where phi^-1 is the quantile function for the normal distribution. The challenge is that some of our p-values are very small (smaller than float64), and we need to compute this in javascript (unless we push to the backend.) 

Hyun pointed out that for small p-values, Z_i^2 has a linear relationship with -log10 p-value. So the idea would be for log p-values below, say, 300 - we use a pure JS implementation of the normal quantile function. For larger log p-values, we use the linear approximation. 

That turns out to work quite well (example code [here](https://github.com/welchr/as241/blob/master/logp_to_z2.js)) except when we try to evaluate exp(Z_i^2). Unfortunately, it seems we can't calculate exp(Z_i^2) when Z_i^2 is > 709 with 64-bit floats. This corresponds to roughly a log p-value of 155. 

This is around where I stopped. I was planning to look into using logp in place of exp(z_i^2) or model it directly but got pulled onto other issues. 

Goncalo also suggested:

> Keep in mind you need to worry about *relative* signals. Find smallest p-value, discard everything larger than min-p * 10^-40 (for example) and then rescale what is left...

That might make more sense than trying to calculate these extreme values.

**Comment by welchr** [comment]
@abought - as we discussed last week, we could move forward with the rest of the implementation details (more general mechanism to allow color to represent things other than LD, such as variants that fall within the credible set). 

As a stopgap until the calculation issue above is fixed, we could just test with reasonably large p-value regions first. 

One other question to consider is where to store the code itself for doing the calculations. Probably does not belong in locuszoom core. 

The credible set can be found by sorting variants by the statistic above in descending order, then taking variants until their statistics sum to >= 0.95.

**Comment by abecasis** [comment]
Two thoughts:

* We probably should start a small library with this sort of functionality.
A summary statistics core library or API. Then, LocusZoom could import it.

* Here is my suggestion on how to handle the calculation with arbitrarily
large z^2.

(pseudo-code)
// Calculate z-squared and store in array
zsquared[i] = ...

// Censor the top p-values
cap = max(zsquared) - 100

// Apply the cap
if (cap > 0)
   for (int i = 0; i < m; i++)
       zsquared[i] = zsquared[i] - cap;           // It is okay for
exponents to be negative

// Calculate the exp
for (int i = 0; i < m; i++)
    e_to_z2[i] = exp(zsquared[i]);

// Calculate the sum and scaling factor only once
denominator = sum(e_to_z2);

// Posterior probabilities
for (int i = 0; i < m; i++)
    e_to_z2[i] /= denominator;

Cheers,

Goncalo

**Comment by abought** [comment]
> One other question to consider is where to store the code itself for doing the calculations. Probably does not belong in locuszoom core.

I'd be open to a standalone library regardless of where we implement the code. (front or backend) If we implement this on the backend, it's worth checking what language the Broad stack uses, to see if the library would be directly usable by them as-is.

Per a back-end implementation, we had gone back and forth about whether or not caching would be feasible in order to improve performance. I had a brief chat with Ben at ASHG, and he pointed out that many of their pages start out at a specific known region- this greatly increases the chance that the user would be hitting a cached pre-calculated region.

(esp if we add some code to pan/zoom at specific discrete steps)

**Comment by welchr** [comment]
One other item I forgot/missed: 

@MrFlick had done some work in implementing the Rstats functions into JS for the conditional branch (https://github.com/statgen/locuszoom/commit/8e3cfd6f4ca032c575162bdbfddb01f84a057526). 
It is currently missing the "qnorm" function, which is basically what ninv is above, but my guess is the relevant code is there to implement it. I think it might make more sense to use that as our "stats" library, rather than my one-off function that I used in testing. 

Then we could do as Goncalo suggests and have a separate library for doing operations on summary statistics.

**Comment by abought** [comment]
This ticket has been addressed as of PR #120 / release 0.7.0. If there are no requests for followup/ revision, I think we can close this ticket.
